(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false}),intro=$('#intro'),options=$('#options'),app=$('#app');
const statusEl=$('#status'),activeNameEl=$('#activeName'),hpEl=$('#hpText'),angleEl=$('#angleText'),powerEl=$('#powerText'),windEl=$('#windText'),timerEl=$('#timerText'),mapEl=$('#mapName'),fireBtn=$('#fire'),msg=$('#message'),classic=$('#classicControls'),touch=$('#touchControls'),touchHint=$('#touchHint');
const W=960,H=540,GRAV=360; canvas.width=W; canvas.height=H;
const terrain=new Uint8Array(W*H),terrainCanvas=document.createElement('canvas'),terrainCtx=terrainCanvas.getContext('2d',{alpha:true}); terrainCanvas.width=W;terrainCanvas.height=H;
let controlMode=localStorage.getItem('mw-control')||'classic',running=false,started=false,last=performance.now(),phase='player',active,projectile=null,turnDelay=0,wind=0,turnTime=30,selectedWeapon='bazooka',mapIndex=-1,mapSeed=0,particles=[],trail=[],shake=0,flash=0,dragAim=false,cloudClock=0;
const localTwoPlayer=()=>window.MW_LOCAL===true;
const held=new Set(),ammo={grenade:3,heavy:1};
const biomes=[
{name:'Grüne Hügel',sky:['#248de3','#d5f1ff'],far:'#6fa6c7',near:'#92bfd3',top:[78,153,62],soil:[94,61,37]},
{name:'Wüsten-Canyon',sky:['#e58b4e','#ffe4af'],far:'#b76a48',near:'#d18c5f',top:[194,151,72],soil:[126,72,46]},
{name:'Felsiges Hochland',sky:['#5e87bb','#d8e6f4'],far:'#5c718a',near:'#7e90a5',top:[102,120,105],soil:[68,71,75]}];
let biome=biomes[0];
const worms=[
{name:'Sheldon',team:'PLAYER',x:150,y:180,vx:0,vy:0,r:18,hp:100,dir:1,angle:42,power:.62,alive:true,onGround:false,groundGrace:0},
{name:'Rollridge',team:'CPU',x:790,y:180,vx:0,vy:0,r:19,hp:100,dir:-1,angle:45,power:.58,alive:true,onGround:false,groundGrace:0}
]; active=worms[0];
const rnd=(a,b)=>a+Math.random()*(b-a), idx=(x,y)=>y*W+x;
function solid(x,y){x|=0;y|=0;return x>=0&&x<W&&y>=0&&y<H&&terrain[idx(x,y)]===1}
function carveCircle(cx,cy,r){const rr=r*r;for(let y=Math.max(0,(cy-r)|0);y<Math.min(H,(cy+r)|0);y++)for(let x=Math.max(0,(cx-r)|0);x<Math.min(W,(cx+r)|0);x++){let dx=x-cx,dy=y-cy;if(dx*dx+dy*dy<=rr)terrain[idx(x,y)]=0}}
function surfaceAt(x){x=Math.max(0,Math.min(W-1,x|0));for(let y=0;y<H;y++)if(solid(x,y))return y;return H}
function generateTerrain(){terrain.fill(0);mapIndex=(mapIndex+1)%biomes.length;biome=biomes[mapIndex];mapSeed=Math.random()*9999;const a=rnd(.008,.014),b=rnd(.021,.039),p1=rnd(0,6.2),p2=rnd(0,6.2),base=rnd(315,350),amp1=rnd(29,48),amp2=rnd(8,18),plateau=Math.random()<.55;for(let x=0;x<W;x++){let s=base+Math.sin(x*a+p1)*amp1+Math.sin(x*b+p2)*amp2;if(plateau&&x>390&&x<570)s-=40+25*Math.sin((x-390)/180*Math.PI);for(let y=Math.max(0,s|0);y<H;y++)terrain[idx(x,y)]=1}for(let i=0;i<2+((Math.random()*3)|0);i++)carveCircle(rnd(250,760),rnd(410,500),rnd(24,55));mapEl.textContent=biome.name;rebuildTerrain()}
function rebuildTerrain(){const im=terrainCtx.createImageData(W,H),d=im.data;for(let y=0;y<H;y++)for(let x=0;x<W;x++){let i=idx(x,y);if(!terrain[i])continue;let o=i*4,near=!solid(x,y-8),top=!solid(x,y-2),rgb=(near||top)?biome.top:biome.soil;let grain=((x*13+y*7)%19)-9;d[o]=Math.max(0,rgb[0]+grain);d[o+1]=Math.max(0,rgb[1]+grain*.55);d[o+2]=Math.max(0,rgb[2]+grain*.35);d[o+3]=255}terrainCtx.clearRect(0,0,W,H);terrainCtx.putImageData(im,0,0);terrainCtx.strokeStyle='rgba(65,125,45,.95)';terrainCtx.lineWidth=6;terrainCtx.beginPath();let drawing=false;for(let x=0;x<W;x+=2){let y=surfaceAt(x);if(y>=H){drawing=false;continue}if(!drawing){terrainCtx.moveTo(x,y);drawing=true}else terrainCtx.lineTo(x,y)}terrainCtx.stroke()}
function hitSamples(x,y,r,extra=0){const rr=r+extra;return [[0,rr],[rr*.72,rr*.65],[-rr*.72,rr*.65],[rr,0],[-rr,0]].some(p=>solid(x+p[0],y+p[1]))}
function safeSpawn(c,x){c.x=x;c.y=Math.max(65,surfaceAt(x)-c.r-2);c.vx=c.vy=0;c.onGround=true;c.groundGrace=.12}
function playerLabel(c){return c===worms[0]?'Spieler 1 · Sheldon':'Spieler 2 · Rollridge'}
function resetGame(){generateTerrain();Object.assign(worms[0],{hp:100,dir:1,angle:42,power:.62,alive:true,onGround:true,groundGrace:.12});Object.assign(worms[1],{hp:100,dir:-1,angle:45,power:.58,alive:true,onGround:true,groundGrace:.12});safeSpawn(worms[0],rnd(95,220));safeSpawn(worms[1],rnd(735,865));active=worms[0];projectile=null;particles=[];trail=[];phase='player';running=true;turnTime=30;wind=Math.round(rnd(-18,18));selectedWeapon='bazooka';ammo.grenade=3;ammo.heavy=1;msg.classList.add('hidden');msg.style.pointerEvents='none';statusEl.textContent=localTwoPlayer()?playerLabel(active):'Dein Zug';syncMode();syncWeapons();syncMeta()}
function syncMeta(){windEl.textContent=`${wind>0?'💨 '+Math.abs(wind)+' →':wind<0?'← '+Math.abs(wind)+' 💨':'· 0 ·'}`;timerEl.textContent=`${Math.ceil(turnTime)}s`}
function syncMode(){classic.classList.toggle('hidden',controlMode!=='classic');touch.classList.toggle('hidden',controlMode!=='touch');touchHint.classList.toggle('hidden',controlMode!=='touch');if(fireBtn)fireBtn.disabled=phase!=='player';if(touchHint&&!touchHint.classList.contains('hidden')&&localTwoPlayer())touchHint.textContent=`${active===worms[0]?'Spieler 1':'Spieler 2'}: Ziehen = Ziel & Stärke · Loslassen = Feuer`}
function syncWeapons(){$$('.weapon').forEach(b=>{const w=b.dataset.weapon;b.classList.toggle('selected',w===selectedWeapon);b.disabled=phase!=='player'||(w==='grenade'&&ammo.grenade<=0)||(w==='heavy'&&ammo.heavy<=0)});$('#ammoGrenade').textContent=ammo.grenade;$('#ammoHeavy').textContent=ammo.heavy}
function start(){intro.classList.add('hidden');options.classList.add('hidden');app.classList.remove('hidden');started=true;resetGame();last=performance.now();requestAnimationFrame(loop)}
$('#startGame').onclick=start;$('#openOptions').onclick=()=>options.classList.remove('hidden');$('#closeOptions').onclick=()=>options.classList.add('hidden');$('#saveOptions').onclick=()=>{controlMode=$('input[name="control"]:checked').value;localStorage.setItem('mw-control',controlMode);options.classList.add('hidden');if(started)syncMode()};const saved=$(`input[name="control"][value="${controlMode}"]`);if(saved)saved.checked=true;
$$('.weapon').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();if(phase!=='player')return;const w=b.dataset.weapon;if((w==='grenade'&&ammo.grenade<=0)||(w==='heavy'&&ammo.heavy<=0))return;selectedWeapon=w;syncWeapons()}));
function updateCharacter(c,dt){if(!c.alive)return;const nearGround=hitSamples(c.x,c.y+1,c.r,5);if(nearGround&&c.vy>=-8){c.onGround=true;c.groundGrace=.12}else{c.groundGrace=Math.max(0,c.groundGrace-dt);c.onGround=c.groundGrace>0}c.vy+=GRAV*dt;let nx=c.x+c.vx*dt;if(!hitSamples(nx,c.y,c.r))c.x=nx;else c.vx*=.08;let ny=c.y+c.vy*dt;if(!hitSamples(c.x,ny,c.r))c.y=ny;else{if(c.vy>0){c.onGround=true;c.groundGrace=.12}c.vy=0;let n=0;while(hitSamples(c.x,c.y,c.r)&&n++<28)c.y-=1}if(c.onGround&&c.vy>0)c.vy=0;c.vx*=Math.pow(.04,dt);if(c.y>H+70){c.hp=0;c.alive=false}}
function input(dt){if(phase!=='player'||projectile||!active.alive)return;const speed=96;if(held.has('left')){active.vx=-speed;active.dir=-1}if(held.has('right')){active.vx=speed;active.dir=1}if(controlMode==='classic'){if(held.has('aimUp'))active.angle=Math.min(85,active.angle+42*dt);if(held.has('aimDown'))active.angle=Math.max(5,active.angle-42*dt);if(held.has('powerUp'))active.power=Math.min(1,active.power+.45*dt);if(held.has('powerDown'))active.power=Math.max(.18,active.power-.45*dt)}}
function jump(){if(phase==='player'&&!projectile&&(active.onGround||active.groundGrace>0)){active.vy=-210;active.onGround=false;active.groundGrace=0}}
function muzzle(c){const a=c.angle*Math.PI/180;return{x:c.x+Math.cos(a)*39*c.dir,y:c.y-Math.sin(a)*39,a}}
function launch(c,weapon){if(projectile||!c.alive)return;const m=muzzle(c),speed=(weapon==='heavy'?185:210)+330*c.power;projectile={x:m.x,y:m.y,vx:Math.cos(m.a)*speed*c.dir,vy:-Math.sin(m.a)*speed,owner:c,life:0,weapon,fuse:weapon==='grenade'?2.7:99,bounces:0};trail=[];phase='projectile';statusEl.textContent=weapon==='grenade'?'Granate tickt…':'Projektil fliegt…';spawn(m.x,m.y,14,'muzzle');syncMode();syncWeapons()}
function fire(c){if(phase!=='player'||projectile||!c.alive)return;const w=selectedWeapon;if(w==='grenade'){if(ammo.grenade<=0)return;ammo.grenade--}if(w==='heavy'){if(ammo.heavy<=0)return;ammo.heavy--}launch(c,w);syncWeapons()}
function spawn(x,y,n,type){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=(type==='boom'?40:20)+Math.random()*(type==='boom'?220:90);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-(type==='boom'?40:20),life:(type==='boom'?.65:.3)+Math.random()*.5,size:2+Math.random()*(type==='boom'?7:4),color:type==='boom'?(i%3===0?'#fff0a5':i%3===1?'#ff9a3d':'#5b2b20'):(i%2?'#fff4b0':'#ff9f43')})}}
function explode(x,y,weapon='bazooka'){const radius=weapon==='heavy'?72:weapon==='grenade'?50:48,range=weapon==='heavy'?145:110,maxDamage=weapon==='heavy'?78:58;carveCircle(x,y,radius);rebuildTerrain();shake=weapon==='heavy'?20:14;flash=1;spawn(x,y,weapon==='heavy'?105:70,'boom');for(const c of worms){if(!c.alive)continue;let dx=c.x-x,dy=c.y-y,d=Math.hypot(dx,dy);if(d<range){let t=1-d/range,damage=Math.max(0,Math.round(maxDamage*t)),inv=1/(d||1);c.hp=Math.max(0,c.hp-damage);c.vx+=dx*inv*(weapon==='heavy'?250:190)*t;c.vy+=dy*inv*190*t-95*t;if(c.hp<=0)c.alive=false}}projectile=null;phase='resolve';turnDelay=1.2;statusEl.textContent='Explosion';syncWeapons()}
function updateProjectile(dt){if(!projectile)return;let p=projectile;p.life+=dt;p.fuse-=dt;p.vx+=wind*3.2*dt;p.vy+=GRAV*.72*dt;let ox=p.x,oy=p.y;p.x+=p.vx*dt;p.y+=p.vy*dt;trail.push({x:p.x,y:p.y,life:.6});if(trail.length>30)trail.shift();if(p.weapon==='grenade'&&p.fuse<=0){explode(p.x,p.y,'grenade');return}if(solid(p.x,p.y)){if(p.weapon==='grenade'&&p.bounces<4){p.x=ox;p.y=oy;p.vy=-Math.abs(p.vy)*.55;p.vx*=.72;p.bounces++}else explode(p.x,p.y,p.weapon)}else if(p.x<0||p.x>=W||p.y>=H){explode(Math.max(0,Math.min(W-1,p.x)),Math.max(0,Math.min(H-1,p.y)),p.weapon)}else if(p.life>8){projectile=null;phase='resolve';turnDelay=.5}}
function updateFx(dt){cloudClock+=dt;for(const p of particles){p.life-=dt;p.vy+=120*dt;p.x+=p.vx*dt;p.y+=p.vy*dt}particles=particles.filter(p=>p.life>0);for(const t of trail)t.life-=dt;trail=trail.filter(t=>t.life>0);flash=Math.max(0,flash-dt*3.2)}
function stable(){return worms.every(c=>!c.alive||(Math.abs(c.vx)<5&&Math.abs(c.vy)<8&&c.onGround))}
function nextTurn(){if(!worms[0].alive||!worms[1].alive)return end();active=active===worms[0]?worms[1]:worms[0];wind=Math.round(rnd(-18,18));turnTime=30;selectedWeapon='bazooka';if(localTwoPlayer()){phase='player';statusEl.textContent=playerLabel(active);syncMode();syncWeapons()}else if(active.team==='CPU'){phase='cpu';statusEl.textContent='Rollridge überlegt…';syncWeapons();setTimeout(cpuTurn,550)}else{phase='player';statusEl.textContent=controlMode==='touch'?'Ziehen und loslassen':'Dein Zug';syncMode();syncWeapons()}syncMeta()}
function cpuTurn(){if(phase!=='cpu'||!worms[1].alive)return;let c=worms[1],t=worms[0];c.dir=t.x<c.x?-1:1;let best={score:1e9,a:45,p:.65};for(let a=18;a<=78;a+=2)for(let p=.30;p<=1;p+=.04){let speed=210+330*p,vx=Math.cos(a*Math.PI/180)*speed*c.dir,vy=-Math.sin(a*Math.PI/180)*speed,x=c.x,y=c.y;for(let tt=0;tt<4.2;tt+=.04){vx+=wind*3.2*.04;vy+=GRAV*.72*.04;x+=vx*.04;y+=vy*.04;if(solid(x,y)||y>H||x<0||x>=W)break;let d=Math.hypot(x-t.x,y-t.y);if(d<best.score)best={score:d,a,p}}}c.angle=Math.max(8,Math.min(82,best.a+rnd(-2.2,2.2)));c.power=Math.max(.2,Math.min(1,best.p+rnd(-.025,.025)));statusEl.textContent=best.score<55?'Rollridge hat dich im Visier…':'Rollridge zielt…';setTimeout(()=>launch(c,'bazooka'),350)}
function end(){running=false;msg.classList.remove('hidden');msg.innerHTML=(worms[0].alive?'🏆 SHELDON GEWINNT!':'🏆 ROLLRIDGE GEWINNT!')+'<br><small>Tippe für neue Welt</small>';msg.style.pointerEvents='auto';msg.onclick=()=>resetGame()}
function cloud(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='rgba(255,255,255,.84)';for(const p of [[0,0,25],[30,-12,35],[67,0,25],[35,8,39]]){ctx.beginPath();ctx.arc(...p,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawBackground(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,biome.sky[0]);g.addColorStop(1,biome.sky[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff0a1';ctx.beginPath();ctx.arc(785,78,32,0,Math.PI*2);ctx.fill();ctx.fillStyle=biome.far;ctx.beginPath();ctx.moveTo(0,330);for(let x=0;x<=W;x+=80)ctx.lineTo(x,245+Math.sin(x*.018+mapSeed)*55);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ctx.fillStyle=biome.near;ctx.beginPath();ctx.moveTo(0,365);for(let x=0;x<=W;x+=70)ctx.lineTo(x,305+Math.sin(x*.024+mapSeed*.7)*42);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();let drift=wind*cloudClock*1.55;for(const c of [[70,95,1.05],[430,130,.78],[700,105,.62]]){let x=((c[0]+drift+1200)%1200)-120;cloud(x,c[1],c[2])}if(Math.abs(wind)>7){ctx.strokeStyle=`rgba(255,255,255,${Math.min(.3,Math.abs(wind)/55)})`;ctx.lineWidth=2;for(let i=0;i<5;i++){let x=((i*210+drift*2)%1100)-70,y=70+i*38;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(wind>0?65:-65),y);ctx.stroke()}}}
function aimGuide(c){if(c!==active||projectile||phase!=='player')return;let m=muzzle(c),speed=(selectedWeapon==='heavy'?185:210)+330*c.power,vx=Math.cos(m.a)*speed*c.dir,vy=-Math.sin(m.a)*speed;for(let i=1;i<=15;i++){let t=i*.085,x=m.x+vx*t+.5*wind*3.2*t*t,y=m.y+vy*t+.5*GRAV*.72*t*t;ctx.globalAlpha=.82-i*.038;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,y,4-i*.12,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function drawFlag(x,y,color='#be452d'){ctx.strokeStyle='#624120';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y+12);ctx.lineTo(x,y-32);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y-30);ctx.lineTo(x+28,y-23);ctx.lineTo(x,y-10);ctx.closePath();ctx.fill();ctx.strokeStyle='#fff8';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x+10,y-21,5,0,Math.PI*2);ctx.stroke()}
function drawCannon(c,baseX,baseY,scale=1){ctx.save();ctx.translate(baseX,baseY);ctx.rotate(-c.angle*Math.PI/180);ctx.fillStyle='#333b39';ctx.strokeStyle='#171d1d';ctx.lineWidth=3;ctx.fillRect(0,-7,35*scale,14*scale);ctx.fillStyle='#778075';ctx.fillRect(25*scale,-9,12*scale,18*scale);ctx.strokeRect(0,-7,37*scale,14*scale);ctx.restore()}
function drawSheldon(c){ctx.save();ctx.translate(c.x,c.y);ctx.scale(c.dir,1);ctx.lineJoin='round';ctx.lineCap='round';ctx.fillStyle='#d7c67a';ctx.strokeStyle='#34291b';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(5,7,25,18,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#59643b';ctx.beginPath();ctx.arc(-8,-7,23,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#b68139';ctx.lineWidth=5;for(let r=8;r<22;r+=7){ctx.beginPath();ctx.arc(-8,-7,r,.2,Math.PI*2.15);ctx.stroke()}ctx.strokeStyle='#3d2d1d';ctx.lineWidth=2;for(let a=0;a<Math.PI*2;a+=Math.PI/4){ctx.beginPath();ctx.moveTo(-8+Math.cos(a)*15,-7+Math.sin(a)*15);ctx.lineTo(-8+Math.cos(a)*22,-7+Math.sin(a)*22);ctx.stroke()}ctx.fillStyle='#9c3f2c';ctx.beginPath();ctx.moveTo(-2,0);ctx.lineTo(18,3);ctx.lineTo(8,16);ctx.lineTo(-8,11);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#5c612d';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(7,-7);ctx.lineTo(8,-30);ctx.moveTo(17,-6);ctx.lineTo(19,-29);ctx.stroke();ctx.fillStyle='#f4f1d4';for(const e of [[8,-34],[20,-33]]){ctx.beginPath();ctx.arc(e[0],e[1],7,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.fillStyle='#17191a';ctx.beginPath();ctx.arc(10,-34,3,0,Math.PI*2);ctx.arc(22,-33,3,0,Math.PI*2);ctx.fill();drawFlag(-25,-19);drawCannon(c,14,-8,.95);ctx.restore()}
function drawRollridge(c){ctx.save();ctx.translate(c.x,c.y);ctx.scale(c.dir,1);ctx.lineJoin='round';ctx.lineCap='round';ctx.fillStyle='#c8bca5';ctx.strokeStyle='#282a2c';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(3,8,27,15,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#65666c';ctx.beginPath();ctx.ellipse(-3,-4,30,24,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#34363a';ctx.lineWidth=2;for(let a=-2.7;a<2.8;a+=.55){ctx.beginPath();ctx.moveTo(-3+Math.cos(a)*7,-4+Math.sin(a)*6);ctx.lineTo(-3+Math.cos(a)*29,-4+Math.sin(a)*23);ctx.stroke()}ctx.strokeStyle='#9b744d';ctx.lineWidth=4;ctx.beginPath();ctx.arc(-3,-4,20,.1,Math.PI*2.15);ctx.stroke();ctx.fillStyle='#eadfca';for(const e of [[15,1],[25,2]]){ctx.beginPath();ctx.arc(e[0],e[1],6,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.fillStyle='#151719';ctx.beginPath();ctx.arc(17,1,3,0,Math.PI*2);ctx.arc(27,2,3,0,Math.PI*2);ctx.fill();drawFlag(-25,-20,'#c45134');ctx.save();ctx.translate(3,-19);ctx.rotate(-.22);ctx.fillStyle='#4c5138';ctx.strokeStyle='#1c2020';ctx.lineWidth=3;ctx.fillRect(0,-7,15,31);ctx.fillStyle='#777c70';ctx.fillRect(-3,-11,21,10);ctx.strokeRect(-3,-11,21,10);ctx.restore();ctx.restore()}
function drawHealth(c){ctx.font='800 14px system-ui';ctx.textAlign='center';ctx.strokeStyle='#102038';ctx.lineWidth=4;ctx.strokeText(c.name,c.x,c.y-54);ctx.fillStyle='#fff';ctx.fillText(c.name,c.x,c.y-54);ctx.fillStyle='#102038bb';ctx.fillRect(c.x-30,c.y-47,60,8);ctx.fillStyle=c.hp>35?'#5de370':'#ff5a50';ctx.fillRect(c.x-30,c.y-47,60*(c.hp/100),8)}
function drawFx(){for(const t of trail){ctx.globalAlpha=Math.max(0,t.life/.6)*.55;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(t.x,t.y,3,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(const p of particles){ctx.globalAlpha=Math.max(0,Math.min(1,p.life*1.8));ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(flash>0){ctx.fillStyle=`rgba(255,235,170,${flash*.32})`;ctx.fillRect(0,0,W,H)}}
function render(){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,W,H);if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.82}drawBackground();ctx.drawImage(terrainCanvas,0,0);aimGuide(active);for(const c of worms){if(!c.alive)continue;if(c.team==='PLAYER')drawSheldon(c);else drawRollridge(c);drawHealth(c)}if(projectile){ctx.fillStyle=projectile.weapon==='grenade'?'#344b31':projectile.weapon==='heavy'?'#633329':'#293745';ctx.beginPath();ctx.arc(projectile.x,projectile.y,projectile.weapon==='heavy'?10:7,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff4cf';ctx.stroke()}drawFx();ctx.restore();activeNameEl.textContent=localTwoPlayer()?playerLabel(active):active.name;hpEl.textContent=Math.round(active.hp)+' / 100';angleEl.textContent=Math.round(active.angle)+'°';powerEl.textContent=Math.round(active.power*100)+'%';syncMeta()}
function update(dt){if(!running)return;input(dt);for(const c of worms)updateCharacter(c,dt);updateProjectile(dt);updateFx(dt);if(phase==='player'&&!projectile){turnTime-=dt;if(turnTime<=0){phase='resolve';turnDelay=.3;statusEl.textContent='Zeit abgelaufen'}}if(phase==='resolve'){turnDelay-=dt;if(turnDelay<=0&&stable())nextTurn()}render()}
function loop(t){if(!started)return;const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);requestAnimationFrame(loop)}
$$('[data-hold]').forEach(b=>{const k=b.dataset.hold,on=e=>{e.preventDefault();held.add(k);b.classList.add('active')},off=e=>{e.preventDefault();held.delete(k);b.classList.remove('active')};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});$$('[data-tap]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();jump()}));if(fireBtn)fireBtn.addEventListener('pointerdown',e=>{e.preventDefault();fire(active)});
function canvasPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}canvas.addEventListener('pointerdown',e=>{if(controlMode!=='touch'||phase!=='player'||projectile)return;e.preventDefault();dragAim=true;canvas.setPointerCapture?.(e.pointerId);touchAim(e)});canvas.addEventListener('pointermove',e=>{if(dragAim&&controlMode==='touch'){e.preventDefault();touchAim(e)}});canvas.addEventListener('pointerup',e=>{if(dragAim&&controlMode==='touch'){e.preventDefault();touchAim(e);dragAim=false;fire(active)}});canvas.addEventListener('pointercancel',()=>dragAim=false);function touchAim(e){const p=canvasPos(e),dx=p.x-active.x,dy=active.y-p.y;if(Math.abs(dx)<8)return;active.dir=dx>=0?1:-1;active.angle=Math.max(5,Math.min(85,Math.atan2(Math.max(5,dy),Math.abs(dx))*180/Math.PI));active.power=Math.max(.18,Math.min(1,Math.hypot(dx,dy)/360))}
addEventListener('keydown',e=>{const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'aimUp',ArrowDown:'aimDown',a:'left',d:'right',w:'aimUp',s:'aimDown',q:'powerDown',e:'powerUp'};if(m[e.key])held.add(m[e.key]);if(e.key===' ')jump();if(e.key==='Enter')fire(active);if(['1','2','3'].includes(e.key)){selectedWeapon={1:'bazooka',2:'grenade',3:'heavy'}[e.key];syncWeapons()}});addEventListener('keyup',e=>{const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'aimUp',ArrowDown:'aimDown',a:'left',d:'right',w:'aimUp',s:'aimDown',q:'powerDown',e:'powerUp'};if(m[e.key])held.delete(m[e.key])});
})();