(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const intro=$('#intro'),options=$('#options'),app=$('#app'),canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false}),statusEl=$('#status'),activeNameEl=$('#activeName'),hpEl=$('#hpText'),angleEl=$('#angleText'),powerEl=$('#powerText'),fireBtn=$('#fire'),msg=$('#message'),classicControls=$('#classicControls'),touchControls=$('#touchControls'),touchHint=$('#touchHint'),mapNameEl=$('#mapName'),windText=$('#windText'),timerText=$('#timerText');
const W=960,H=540,GRAV=360;canvas.width=W;canvas.height=H;
let controlMode=localStorage.getItem('mw-control')||'classic',terrain=new Uint8Array(W*H),running=false,last=performance.now(),projectile=null,phase='player',turnDelay=0,shake=0,flash=0,particles=[],trail=[],dragAim=false,gameStarted=false,selectedWeapon='bazooka',wind=0,turnTime=30,mapIndex=-1,mapSeed=0;
const held=new Set(),ammo={grenade:3,heavy:1};
const biomes=[
{name:'Grüne Hügel',sky:['#4a9be8','#bde9ff'],far:'#7ca9c7',near:'#9fc8dc',top:[76,151,61],soil:[91,63,39],accent:'#63bd62'},
{name:'Wüsten-Canyon',sky:['#f19a55','#ffe6b0'],far:'#b96e4a',near:'#d39564',top:[190,151,74],soil:[123,73,48],accent:'#d4a04e'},
{name:'Felsiges Hochland',sky:['#688fc5','#d5e4f4'],far:'#566d88',near:'#788aa0',top:[101,120,105],soil:[69,72,76],accent:'#758878'}];
let biome=biomes[0];
const worms=[{name:'Sheldon',team:'PLAYER',x:150,y:180,vx:0,vy:0,r:16,hp:100,dir:1,angle:42,power:.62,color:'#62d56b',belly:'#b7f38f',shell:'#8b5a2b',shell2:'#f0a43c',alive:true,onGround:false},{name:'Rollridge',team:'CPU',x:790,y:180,vx:0,vy:0,r:17,hp:100,dir:-1,angle:45,power:.58,color:'#60bff2',belly:'#b8ecff',shell:'#a43d30',shell2:'#f07d4f',alive:true,onGround:false}];
let active=worms[0];
function rnd(a,b){return a+Math.random()*(b-a)}function idx(x,y){return y*W+x}function solid(x,y){x|=0;y|=0;return x>=0&&x<W&&y>=0&&y<H&&terrain[idx(x,y)]===1}
function carveCircle(cx,cy,r){let r2=r*r;for(let y=Math.max(0,(cy-r)|0);y<Math.min(H,(cy+r)|0);y++)for(let x=Math.max(0,(cx-r)|0);x<Math.min(W,(cx+r)|0);x++){let dx=x-cx,dy=y-cy;if(dx*dx+dy*dy<=r2)terrain[idx(x,y)]=0}}
function surfaceAt(x){x=Math.max(0,Math.min(W-1,x|0));for(let y=0;y<H;y++)if(solid(x,y))return y;return H}
function generateTerrain(){terrain.fill(0);mapIndex=(mapIndex+1)%biomes.length;biome=biomes[mapIndex];mapSeed=Math.random()*9999;let a=rnd(.008,.015),b=rnd(.022,.04),p1=rnd(0,6.2),p2=rnd(0,6.2),base=rnd(315,350),amp1=rnd(28,48),amp2=rnd(8,19),plateau=Math.random()<.55;for(let x=0;x<W;x++){let s=base+Math.sin(x*a+p1)*amp1+Math.sin(x*b+p2)*amp2;if(plateau&&x>390&&x<570)s-=rnd(32,68);if(Math.random()<.002)s-=rnd(8,18);for(let y=Math.max(0,s|0);y<H;y++)terrain[idx(x,y)]=1}for(let i=0;i<2+((Math.random()*3)|0);i++)carveCircle(rnd(250,760),rnd(405,500),rnd(24,55));mapNameEl.textContent=biome.name}
function hits(x,y,r){return [[0,r],[r*.75,r*.65],[-r*.75,r*.65],[r,0],[-r,0]].some(p=>solid(x+p[0],y+p[1]))}function ground(c){c.y=Math.min(c.y,surfaceAt(c.x)-c.r-1)}
function safeSpawn(c,x){c.x=x;c.y=Math.max(70,surfaceAt(x)-c.r-2);c.vx=c.vy=0}
function resetGame(){generateTerrain();Object.assign(worms[0],{hp:100,dir:1,angle:42,power:.62,alive:true,onGround:false});Object.assign(worms[1],{hp:100,dir:-1,angle:45,power:.58,alive:true,onGround:false});safeSpawn(worms[0],rnd(95,220));safeSpawn(worms[1],rnd(735,865));active=worms[0];projectile=null;particles=[];trail=[];phase='player';running=true;turnTime=30;wind=Math.round(rnd(-18,18));selectedWeapon='bazooka';ammo.grenade=3;ammo.heavy=1;msg.classList.add('hidden');msg.style.pointerEvents='none';statusEl.textContent='Dein Zug';syncMode();syncWeapons();syncMeta()}
function syncMeta(){windText.textContent=`Wind ${wind>0?'→':wind<0?'←':'·'} ${Math.abs(wind)}`;timerText.textContent=`${Math.ceil(turnTime)}s`}
function syncMode(){classicControls.classList.toggle('hidden',controlMode!=='classic');touchControls.classList.toggle('hidden',controlMode!=='touch');touchHint.classList.toggle('hidden',controlMode!=='touch');if(fireBtn)fireBtn.disabled=phase!=='player'}
function syncWeapons(){$$('.weapon').forEach(b=>{b.classList.toggle('selected',b.dataset.weapon===selectedWeapon);let w=b.dataset.weapon;b.disabled=(w==='grenade'&&ammo.grenade<=0)||(w==='heavy'&&ammo.heavy<=0)||phase!=='player'});$('#ammoGrenade').textContent=ammo.grenade;$('#ammoHeavy').textContent=ammo.heavy}
function start(){intro.classList.add('hidden');options.classList.add('hidden');app.classList.remove('hidden');gameStarted=true;resetGame();last=performance.now();requestAnimationFrame(loop)}
$('#startGame').onclick=start;$('#openOptions').onclick=()=>options.classList.remove('hidden');$('#closeOptions').onclick=()=>options.classList.add('hidden');$('#saveOptions').onclick=()=>{controlMode=$('input[name="control"]:checked').value;localStorage.setItem('mw-control',controlMode);options.classList.add('hidden');if(gameStarted)syncMode()};let saved=$(`input[name="control"][value="${controlMode}"]`);if(saved)saved.checked=true;
$$('.weapon').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();if(phase!=='player')return;let w=b.dataset.weapon;if((w==='grenade'&&ammo.grenade<=0)||(w==='heavy'&&ammo.heavy<=0))return;selectedWeapon=w;syncWeapons()}));
function updateCharacter(c,dt){if(!c.alive)return;c.onGround=hits(c.x,c.y+2,c.r);if(c.onGround&&c.vy>0)c.vy=0;c.vy+=GRAV*dt;let nx=c.x+c.vx*dt;if(!hits(nx,c.y,c.r))c.x=nx;else c.vx*=.1;let ny=c.y+c.vy*dt;if(!hits(c.x,ny,c.r))c.y=ny;else{if(c.vy>0)c.onGround=true;c.vy=0;let g=0;while(hits(c.x,c.y,c.r)&&g++<25)c.y-=1}c.vx*=Math.pow(.04,dt);if(c.y>H+70){c.hp=0;c.alive=false}}
function input(dt){if(phase!=='player'||projectile||!active.alive)return;const speed=95;if(held.has('left')){active.vx=-speed;active.dir=-1}if(held.has('right')){active.vx=speed;active.dir=1}if(controlMode==='classic'){if(held.has('aimUp'))active.angle=Math.min(85,active.angle+42*dt);if(held.has('aimDown'))active.angle=Math.max(5,active.angle-42*dt);if(held.has('powerUp'))active.power=Math.min(1,active.power+.45*dt);if(held.has('powerDown'))active.power=Math.max(.18,active.power-.45*dt)}}
function jump(){if(phase==='player'&&!projectile&&active.onGround){active.vy=-205;active.onGround=false}}
function muzzle(c){const a=c.angle*Math.PI/180;return{x:c.x+Math.cos(a)*29*c.dir,y:c.y-Math.sin(a)*29,a}}
function launch(c,weapon){if(projectile||!c.alive)return;let m=muzzle(c),speed=(weapon==='heavy'?185:210)+330*c.power;projectile={x:m.x,y:m.y,vx:Math.cos(m.a)*speed*c.dir,vy:-Math.sin(m.a)*speed,owner:c,life:0,weapon,fuse:weapon==='grenade'?2.7:99,bounces:0};trail=[];phase='projectile';statusEl.textContent=weapon==='grenade'?'Granate tickt…':'Projektil fliegt…';spawn(m.x,m.y,14,'muzzle');syncMode();syncWeapons()}
function fire(c){if(phase!=='player'||projectile||!c.alive)return;let w=selectedWeapon;if(w==='grenade'){if(ammo.grenade<=0)return;ammo.grenade--}if(w==='heavy'){if(ammo.heavy<=0)return;ammo.heavy--}launch(c,w);syncWeapons()}
function spawn(x,y,n,type){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=(type==='boom'?40:20)+Math.random()*(type==='boom'?220:90);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-(type==='boom'?40:20),life:(type==='boom'?.65:.3)+Math.random()*.5,size:2+Math.random()*(type==='boom'?7:4),color:type==='boom'?(i%3===0?'#fff0a5':i%3===1?'#ff9a3d':'#5b2b20'):(i%2?'#fff4b0':'#ff9f43')})}}
function explode(x,y,weapon='bazooka'){let radius=weapon==='heavy'?72:weapon==='grenade'?50:48,range=weapon==='heavy'?145:110,maxDamage=weapon==='heavy'?78:58;carveCircle(x,y,radius);shake=weapon==='heavy'?20:14;flash=1;spawn(x,y,weapon==='heavy'?105:70,'boom');for(const c of worms){if(!c.alive)continue;let dx=c.x-x,dy=c.y-y,d=Math.hypot(dx,dy);if(d<range){let t=1-d/range,damage=Math.max(0,Math.round(maxDamage*t)),inv=1/(d||1);c.hp=Math.max(0,c.hp-damage);c.vx+=dx*inv*(weapon==='heavy'?250:190)*t;c.vy+=dy*inv*190*t-95*t;if(c.hp<=0)c.alive=false}}projectile=null;phase='resolve';turnDelay=1.2;statusEl.textContent='Explosion';syncWeapons()}
function updateProjectile(dt){if(!projectile)return;let p=projectile;p.life+=dt;p.fuse-=dt;p.vx+=wind*3.2*dt;p.vy+=GRAV*.72*dt;let ox=p.x,oy=p.y;p.x+=p.vx*dt;p.y+=p.vy*dt;trail.push({x:p.x,y:p.y,life:.6});if(trail.length>30)trail.shift();if(p.weapon==='grenade'&&p.fuse<=0){explode(p.x,p.y,'grenade');return}if(solid(p.x,p.y)){if(p.weapon==='grenade'&&p.bounces<4){p.x=ox;p.y=oy;p.vy=-Math.abs(p.vy)*.55;p.vx*=.72;p.bounces++;}else explode(p.x,p.y,p.weapon)}else if(p.x<0||p.x>=W||p.y>=H){if(p.weapon==='grenade'&&p.fuse>0&&p.y<H){p.vx*=-.45;p.x=Math.max(2,Math.min(W-3,p.x));p.bounces++}else explode(Math.max(0,Math.min(W-1,p.x)),Math.max(0,Math.min(H-1,p.y)),p.weapon)}else if(p.life>8){projectile=null;phase='resolve';turnDelay=.5}}
function updateFx(dt){for(const p of particles){p.life-=dt;p.vy+=120*dt;p.x+=p.vx*dt;p.y+=p.vy*dt}particles=particles.filter(p=>p.life>0);for(const t of trail)t.life-=dt;trail=trail.filter(t=>t.life>0);flash=Math.max(0,flash-dt*3.2)}function stable(){return worms.every(c=>!c.alive||(Math.abs(c.vx)<5&&Math.abs(c.vy)<8&&c.onGround))}
function nextTurn(){if(!worms[0].alive||!worms[1].alive)return end();active=active===worms[0]?worms[1]:worms[0];wind=Math.round(rnd(-18,18));turnTime=30;if(active.team==='CPU'){phase='cpu';statusEl.textContent='Rollridge überlegt…';syncWeapons();setTimeout(cpuTurn,600)}else{phase='player';statusEl.textContent=controlMode==='touch'?'Ziehen und loslassen':'Dein Zug';selectedWeapon='bazooka';syncMode();syncWeapons()}syncMeta()}
function cpuTurn(){if(phase!=='cpu'||!worms[1].alive)return;let c=worms[1],t=worms[0];c.dir=t.x<c.x?-1:1;let best={score:1e9,a:45,p:.65};for(let a=18;a<=78;a+=2)for(let p=.30;p<=1;p+=.04){let speed=210+330*p,vx=Math.cos(a*Math.PI/180)*speed*c.dir,vy=-Math.sin(a*Math.PI/180)*speed,x=c.x,y=c.y;for(let tt=0;tt<4.2;tt+=.04){vx+=wind*3.2*.04;vy+=GRAV*.72*.04;x+=vx*.04;y+=vy*.04;if(solid(x,y)||y>H||x<0||x>=W)break;let d=Math.hypot(x-t.x,y-t.y);if(d<best.score)best={score:d,a,p}}}c.angle=Math.max(8,Math.min(82,best.a+rnd(-2.2,2.2)));c.power=Math.max(.2,Math.min(1,best.p+rnd(-.025,.025)));statusEl.textContent=best.score<55?'Rollridge hat dich im Visier…':'Rollridge zielt…';setTimeout(()=>launch(c,'bazooka'),350)}
function end(){running=false;msg.classList.remove('hidden');msg.innerHTML=(worms[0].alive?'🏆 SHELDON GEWINNT!':'🏆 ROLLRIDGE GEWINNT!')+'<br><small>Tippe für neue Welt</small>';msg.style.pointerEvents='auto';msg.onclick=()=>resetGame()}
function drawBackground(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,biome.sky[0]);g.addColorStop(1,biome.sky[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff6b0cc';ctx.beginPath();ctx.arc(790,80,35,0,7);ctx.fill();ctx.fillStyle=biome.far;ctx.beginPath();ctx.moveTo(0,315);for(let x=0;x<=W;x+=90)ctx.lineTo(x,245+Math.sin(x*.018+mapSeed)*55);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ctx.fillStyle=biome.near;ctx.beginPath();ctx.moveTo(0,355);for(let x=0;x<=W;x+=75)ctx.lineTo(x,300+Math.sin(x*.024+mapSeed*.7)*40);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();cloud(120,88,1.05);cloud(610,120,.8)}
function cloud(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#ffffffd8';for(const c of [[0,0,28],[32,-12,38],[72,1,27],[36,8,43]]){ctx.beginPath();ctx.arc(c[0],c[1],c[2],0,7);ctx.fill()}ctx.restore()}
function drawTerrain(){let img=ctx.createImageData(W,H),d=img.data;for(let y=0;y<H;y++)for(let x=0;x<W;x++){let i=idx(x,y);if(!terrain[i])continue;let o=i*4,top=!solid(x,y-2),near=!solid(x,y-8),rgb=near?biome.top:biome.soil;if(top)rgb=biome.top;d[o]=rgb[0];d[o+1]=rgb[1];d[o+2]=rgb[2];d[o+3]=255}ctx.putImageData(img,0,0)}
function aimGuide(c){if(c!==active||projectile||phase!=='player')return;let m=muzzle(c),speed=(selectedWeapon==='heavy'?185:210)+330*c.power,vx=Math.cos(m.a)*speed*c.dir,vy=-Math.sin(m.a)*speed;for(let i=1;i<=12;i++){let t=i*.095,x=m.x+vx*t+.5*wind*3.2*t*t,y=m.y+vy*t+.5*GRAV*.72*t*t;ctx.globalAlpha=.75-i*.045;ctx.fillStyle=selectedWeapon==='grenade'?'#ffe36d':'#fff';ctx.beginPath();ctx.arc(x,y,4-i*.15,0,7);ctx.fill()}ctx.globalAlpha=1}
function worm(c){if(!c.alive)return;ctx.save();ctx.translate(c.x,c.y);ctx.scale(c.dir,1);ctx.strokeStyle='#162033';ctx.lineWidth=3;ctx.fillStyle=c.color;ctx.beginPath();ctx.ellipse(2,5,23,15,-.05,0,7);ctx.fill();ctx.stroke();ctx.fillStyle=c.belly;ctx.beginPath();ctx.ellipse(10,9,12,7,0,0,7);ctx.fill();ctx.fillStyle=c.shell;ctx.beginPath();ctx.arc(-6,-5,15,0,7);ctx.fill();ctx.stroke();ctx.strokeStyle=c.shell2;ctx.beginPath();ctx.arc(-6,-5,9,.3,Math.PI*2.3);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(11,-10,5.5,0,7);ctx.arc(19,-9,5.5,0,7);ctx.fill();ctx.fillStyle='#182033';ctx.beginPath();ctx.arc(13,-10,2.2,0,7);ctx.arc(21,-9,2.2,0,7);ctx.fill();if(c===active&&!projectile&&phase==='player'){ctx.rotate(-(c.angle*Math.PI/180));ctx.fillStyle=selectedWeapon==='heavy'?'#6c432f':selectedWeapon==='grenade'?'#334d37':'#37465e';ctx.fillRect(12,-5,24,9)}ctx.restore();ctx.font='800 15px system-ui';ctx.textAlign='center';ctx.strokeStyle='#102038';ctx.lineWidth=4;ctx.strokeText(c.name,c.x,c.y-42);ctx.fillStyle='#fff';ctx.fillText(c.name,c.x,c.y-42);ctx.fillStyle='#102038aa';ctx.fillRect(c.x-27,c.y-35,54,7);ctx.fillStyle=c.hp>35?'#59df72':'#ff5c53';ctx.fillRect(c.x-27,c.y-35,54*(c.hp/100),7)}
function drawFx(){for(const t of trail){ctx.globalAlpha=Math.max(0,t.life/.6)*.55;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(t.x,t.y,3,0,7);ctx.fill()}ctx.globalAlpha=1;for(const p of particles){ctx.globalAlpha=Math.max(0,Math.min(1,p.life*1.8));ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,7);ctx.fill()}ctx.globalAlpha=1;if(flash>0){ctx.fillStyle=`rgba(255,235,170,${flash*.32})`;ctx.fillRect(0,0,W,H)}}
function render(){ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.82}drawBackground();drawTerrain();aimGuide(active);for(const c of worms)worm(c);if(projectile){ctx.fillStyle=projectile.weapon==='grenade'?'#2f4b32':projectile.weapon==='heavy'?'#6a3427':'#283544';ctx.beginPath();ctx.arc(projectile.x,projectile.y,projectile.weapon==='heavy'?10:7,0,7);ctx.fill();ctx.strokeStyle='#fff4cf';ctx.stroke()}drawFx();ctx.restore();activeNameEl.textContent=active.name;hpEl.textContent=Math.round(active.hp)+' HP';angleEl.textContent=Math.round(active.angle)+'°';powerEl.textContent=Math.round(active.power*100)+'%';syncMeta()}
function update(dt){if(!running)return;input(dt);for(const c of worms)updateCharacter(c,dt);updateProjectile(dt);updateFx(dt);if(phase==='player'&&!projectile){turnTime-=dt;if(turnTime<=0){phase='resolve';turnDelay=.3;statusEl.textContent='Zeit abgelaufen'}}if(phase==='resolve'){turnDelay-=dt;if(turnDelay<=0&&stable())nextTurn()}render()}
function loop(t){if(!gameStarted)return;let dt=Math.min(.033,(t-last)/1000);last=t;update(dt);requestAnimationFrame(loop)}
$$('[data-hold]').forEach(b=>{let k=b.dataset.hold,on=e=>{e.preventDefault();held.add(k);b.classList.add('active')},off=e=>{e.preventDefault();held.delete(k);b.classList.remove('active')};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});$$('[data-tap]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();jump()}));if(fireBtn)fireBtn.addEventListener('pointerdown',e=>{e.preventDefault();fire(active)});
function canvasPos(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}canvas.addEventListener('pointerdown',e=>{if(controlMode!=='touch'||phase!=='player'||projectile)return;e.preventDefault();dragAim=true;canvas.setPointerCapture?.(e.pointerId);touchAim(e)});canvas.addEventListener('pointermove',e=>{if(dragAim&&controlMode==='touch'){e.preventDefault();touchAim(e)}});canvas.addEventListener('pointerup',e=>{if(dragAim&&controlMode==='touch'){e.preventDefault();touchAim(e);dragAim=false;fire(active)}});canvas.addEventListener('pointercancel',()=>dragAim=false);function touchAim(e){let p=canvasPos(e),dx=p.x-active.x,dy=active.y-p.y;if(Math.abs(dx)<8)return;active.dir=dx>=0?1:-1;active.angle=Math.max(5,Math.min(85,Math.atan2(Math.max(5,dy),Math.abs(dx))*180/Math.PI));active.power=Math.max(.18,Math.min(1,Math.hypot(dx,dy)/360))}
addEventListener('keydown',e=>{let m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'aimUp',ArrowDown:'aimDown',a:'left',d:'right',w:'aimUp',s:'aimDown',q:'powerDown',e:'powerUp'};if(m[e.key])held.add(m[e.key]);if(e.key===' ')jump();if(e.key==='Enter')fire(active);if(['1','2','3'].includes(e.key)){selectedWeapon={1:'bazooka',2:'grenade',3:'heavy'}[e.key];syncWeapons()}});addEventListener('keyup',e=>{let m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'aimUp',ArrowDown:'aimDown',a:'left',d:'right',w:'aimUp',s:'aimDown',q:'powerDown',e:'powerUp'};if(m[e.key])held.delete(m[e.key])});
})();