(()=>{
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d',{alpha:false});
const statusEl=document.getElementById('status'),activeNameEl=document.getElementById('activeName'),hpEl=document.getElementById('hpText'),angleEl=document.getElementById('angleText'),powerEl=document.getElementById('powerText'),fireBtn=document.getElementById('fire'),msg=document.getElementById('message');
const W=960,H=540,GROUND=330,GRAV=360;canvas.width=W;canvas.height=H;
let terrain=new Uint8Array(W*H),running=true,last=performance.now(),projectile=null,phase='player',turnDelay=0,shake=0,flash=0,particles=[],trail=[];
const held=new Set();
const worms=[
{name:'Sheldon',team:'PLAYER',x:150,y:180,vx:0,vy:0,r:16,hp:100,dir:1,angle:42,power:.62,color:'#62d56b',belly:'#b7f38f',shell:'#8b5a2b',shell2:'#f0a43c',alive:true,onGround:false},
{name:'Rollridge',team:'CPU',x:790,y:180,vx:0,vy:0,r:17,hp:100,dir:-1,angle:45,power:.58,color:'#60bff2',belly:'#b8ecff',shell:'#a43d30',shell2:'#f07d4f',alive:true,onGround:false}
];
let active=worms[0];
function idx(x,y){return y*W+x}function solid(x,y){x=x|0;y=y|0;return x>=0&&x<W&&y>=0&&y<H&&terrain[idx(x,y)]===1}
function generateTerrain(){terrain.fill(0);for(let x=0;x<W;x++){let surface=GROUND+Math.sin(x*.012)*35+Math.sin(x*.031)*12;surface+=x>400&&x<570?-55:0;for(let y=Math.max(0,surface|0);y<H;y++)terrain[idx(x,y)]=1}carveCircle(480,410,52);carveCircle(660,455,38)}
function carveCircle(cx,cy,r){const r2=r*r;for(let y=Math.max(0,(cy-r)|0);y<Math.min(H,(cy+r)|0);y++)for(let x=Math.max(0,(cx-r)|0);x<Math.min(W,(cx+r)|0);x++){let dx=x-cx,dy=y-cy;if(dx*dx+dy*dy<=r2)terrain[idx(x,y)]=0}}
function resize(){const rect=canvas.parentElement.getBoundingClientRect();if(rect.width&&rect.height){canvas.style.width=rect.width+'px';canvas.style.height=rect.height+'px'}}addEventListener('resize',resize);
function terrainSurfaceAt(x){x=Math.max(0,Math.min(W-1,x|0));for(let y=0;y<H;y++)if(solid(x,y))return y;return H}
function groundCharacter(c){c.y=Math.min(c.y,terrainSurfaceAt(c.x)-c.r-1)}
function circleHitsTerrain(x,y,r){const pts=[[0,r],[r*.75,r*.65],[-r*.75,r*.65],[r,0],[-r,0]];return pts.some(p=>solid(x+p[0],y+p[1]))}
function updateCharacter(c,dt){if(!c.alive)return;c.onGround=circleHitsTerrain(c.x,c.y+2,c.r);if(c.onGround&&c.vy>0)c.vy=0;c.vy+=GRAV*dt;let nx=c.x+c.vx*dt;if(!circleHitsTerrain(nx,c.y,c.r))c.x=nx;else c.vx*=.1;let ny=c.y+c.vy*dt;if(!circleHitsTerrain(c.x,ny,c.r))c.y=ny;else{if(c.vy>0)c.onGround=true;c.vy=0;let guard=0;while(circleHitsTerrain(c.x,c.y,c.r)&&guard++<25)c.y-=1}c.vx*=Math.pow(.04,dt);if(c.y>H+80){c.hp=0;c.alive=false}}
function playerInput(dt){if(phase!=='player'||projectile||!active.alive)return;const speed=95;if(held.has('left')){active.vx=-speed;active.dir=-1}if(held.has('right')){active.vx=speed;active.dir=1}if(held.has('aimUp'))active.angle=Math.min(85,active.angle+42*dt);if(held.has('aimDown'))active.angle=Math.max(5,active.angle-42*dt);if(held.has('powerUp'))active.power=Math.min(1,active.power+.45*dt);if(held.has('powerDown'))active.power=Math.max(.18,active.power-.45*dt)}
function jump(){if(phase==='player'&&!projectile&&active.onGround){active.vy=-205;active.onGround=false}}
function muzzle(c){const a=(c.angle*Math.PI/180)*c.dir;return{x:c.x+Math.cos(a)*29,y:c.y-Math.sin(Math.abs(a))*29,a}}
function fire(c){if(projectile||!c.alive)return;const m=muzzle(c),speed=210+330*c.power;projectile={x:m.x,y:m.y,vx:Math.cos(m.a)*speed,vy:-Math.sin(Math.abs(m.a))*speed,owner:c,life:0};trail=[];phase='projectile';fireBtn.disabled=true;statusEl.textContent='Projektil fliegt…';spawnMuzzle(m.x,m.y)}
function spawnMuzzle(x,y){for(let i=0;i<12;i++)particles.push({x,y,vx:(Math.random()-.5)*90,vy:(Math.random()-.5)*90-25,life:.35+Math.random()*.25,size:2+Math.random()*4,color:i<5?'#fff4b0':'#ff9f43'})}
function spawnExplosion(x,y){flash=1;for(let i=0;i<70;i++){const a=Math.random()*Math.PI*2,s=35+Math.random()*210;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-40,life:.55+Math.random()*.65,size:2+Math.random()*7,color:i%3===0?'#fff0a5':i%3===1?'#ff9a3d':'#5b2b20'})}}
function explode(x,y){carveCircle(x,y,48);shake=14;spawnExplosion(x,y);for(const c of worms){if(!c.alive)continue;const dx=c.x-x,dy=c.y-y,d=Math.hypot(dx,dy);if(d<110){const t=1-d/110,damage=Math.max(0,Math.round(58*t));c.hp=Math.max(0,c.hp-damage);const inv=1/(d||1);c.vx+=dx*inv*190*t;c.vy+=dy*inv*190*t-90*t;if(c.hp<=0)c.alive=false}}projectile=null;phase='resolve';turnDelay=1.25;statusEl.textContent='Explosion – Physik wird aufgelöst'}
function updateProjectile(dt){if(!projectile)return;const p=projectile;p.life+=dt;p.vy+=GRAV*.72*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;trail.push({x:p.x,y:p.y,life:.6});if(trail.length>28)trail.shift();if(solid(p.x,p.y)||p.x<0||p.x>=W||p.y>=H)explode(Math.max(0,Math.min(W-1,p.x)),Math.max(0,Math.min(H-1,p.y)));else if(p.life>7){projectile=null;phase='resolve';turnDelay=.7}}
function updateFx(dt){for(const p of particles){p.life-=dt;p.vy+=120*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.985}particles=particles.filter(p=>p.life>0);for(const t of trail)t.life-=dt;trail=trail.filter(t=>t.life>0);flash=Math.max(0,flash-dt*3.2)}
function stable(){return worms.every(c=>!c.alive||(Math.abs(c.vx)<5&&Math.abs(c.vy)<8&&c.onGround))}
function nextTurn(){if(!worms[0].alive||!worms[1].alive){showEnd();return}active=active===worms[0]?worms[1]:worms[0];if(active.team==='CPU'){phase='cpu';fireBtn.disabled=true;statusEl.textContent='Rollridge überlegt…';setTimeout(cpuTurn,700)}else{phase='player';fireBtn.disabled=false;statusEl.textContent='Dein Zug – bewegen, zielen, feuern'}}
function cpuTurn(){if(phase!=='cpu'||!worms[1].alive)return;const c=worms[1],t=worms[0];c.dir=t.x<c.x?-1:1;let best={score:1e9,a:45,p:.65};for(let a=20;a<=75;a+=2)for(let p=.35;p<=.95;p+=.05){const speed=210+330*p,vx=Math.cos(a*Math.PI/180)*speed,vy=-Math.sin(a*Math.PI/180)*speed;let x=c.x,y=c.y,xx=vx*c.dir,yy=vy;for(let tt=0;tt<3.2;tt+=.045){yy+=GRAV*.72*.045;x+=xx*.045;y+=yy*.045;if(solid(x,y)||y>H)break;const d=Math.hypot(x-t.x,y-t.y);if(d<best.score)best={score:d,a,p}}}c.angle=best.a;c.power=best.p;setTimeout(()=>fire(c),450)}
function showEnd(){running=false;msg.classList.remove('hidden');msg.innerHTML=worms[0].alive?'🏆 SHELDON GEWINNT!<br><small>Tippe zum Neustart</small>':'🏆 ROLLRIDGE GEWINNT!<br><small>Tippe zum Neustart</small>';statusEl.textContent='Match beendet';msg.style.pointerEvents='auto';msg.onclick=()=>location.reload()}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#4a9be8');g.addColorStop(.62,'#a9dcff');g.addColorStop(1,'#e8f5ff');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const sun=ctx.createRadialGradient(775,85,2,775,85,70);sun.addColorStop(0,'#fffbd0');sun.addColorStop(.2,'#ffe99b');sun.addColorStop(1,'#ffe99b00');ctx.fillStyle=sun;ctx.beginPath();ctx.arc(775,85,70,0,7);ctx.fill();ctx.fillStyle='#7ca9c7aa';ctx.beginPath();ctx.moveTo(0,315);ctx.lineTo(110,205);ctx.lineTo(210,298);ctx.lineTo(315,190);ctx.lineTo(425,305);ctx.lineTo(540,220);ctx.lineTo(690,310);ctx.lineTo(820,205);ctx.lineTo(960,300);ctx.lineTo(960,540);ctx.lineTo(0,540);ctx.fill();ctx.fillStyle='#9fc8dcaa';ctx.beginPath();ctx.moveTo(0,345);ctx.lineTo(180,265);ctx.lineTo(340,342);ctx.lineTo(530,250);ctx.lineTo(710,340);ctx.lineTo(865,270);ctx.lineTo(960,330);ctx.lineTo(960,540);ctx.lineTo(0,540);ctx.fill();drawCloud(120,88,1.05);drawCloud(620,120,.82)}
function drawCloud(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#ffffffd9';for(const c of [[0,0,28],[32,-12,38],[72,1,27],[36,8,43]]){ctx.beginPath();ctx.arc(c[0],c[1],c[2],0,7);ctx.fill()}ctx.restore()}
function drawTerrain(){const img=ctx.createImageData(W,H),d=img.data;for(let y=0;y<H;y++)for(let x=0;x<W;x++){const i=idx(x,y);if(!terrain[i])continue;const o=i*4,top=!solid(x,y-2),nearTop=!solid(x,y-8);let r=89,g=63,b=39;if(nearTop){r=116;g=83;b=47}if(top){r=88;g=148;b=58}d[o]=r;d[o+1]=g;d[o+2]=b;d[o+3]=255}ctx.putImageData(img,0,0);ctx.globalAlpha=.12;ctx.fillStyle='#000';for(let x=20;x<W;x+=48){let y=terrainSurfaceAt(x);ctx.fillRect(x,y+22,3,18+((x*13)%28))}ctx.globalAlpha=1}
function drawAimGuide(c){if(c!==active||projectile)return;const m=muzzle(c),speed=210+330*c.power,vx=Math.cos(m.a)*speed,vy=-Math.sin(Math.abs(m.a))*speed;ctx.save();for(let i=1;i<=11;i++){const t=i*.095,x=m.x+vx*t,y=m.y+vy*t+.5*GRAV*.72*t*t;ctx.globalAlpha=.72-i*.045;ctx.fillStyle=i<4?'#fff6cf':'#ffffff';ctx.beginPath();ctx.arc(x,y,4-i*.15,0,7);ctx.fill()}ctx.restore()}
function drawWorm(c){if(!c.alive)return;ctx.save();ctx.translate(c.x,c.y);ctx.scale(c.dir,1);ctx.strokeStyle='#162033';ctx.lineWidth=3;ctx.lineJoin='round';ctx.fillStyle='#0003';ctx.beginPath();ctx.ellipse(0,17,24,7,0,0,7);ctx.fill();ctx.fillStyle=c.color;ctx.beginPath();ctx.ellipse(2,5,23,15,-.05,0,7);ctx.fill();ctx.stroke();ctx.fillStyle=c.belly;ctx.beginPath();ctx.ellipse(10,9,12,7,0,0,7);ctx.fill();ctx.fillStyle=c.shell;ctx.beginPath();ctx.arc(-6,-5,15,0,7);ctx.fill();ctx.stroke();ctx.strokeStyle=c.shell2;ctx.lineWidth=3;ctx.beginPath();ctx.arc(-6,-5,9,.3,Math.PI*2.3);ctx.stroke();ctx.fillStyle='#f8fbff';ctx.strokeStyle='#162033';ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(11,-10,5.5,0,7);ctx.arc(19,-9,5.5,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#182033';ctx.beginPath();ctx.arc(13,-10,2.2,0,7);ctx.arc(21,-9,2.2,0,7);ctx.fill();ctx.strokeStyle='#25324a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(10,-14);ctx.lineTo(7,-25);ctx.moveTo(18,-13);ctx.lineTo(21,-24);ctx.stroke();ctx.fillStyle='#273750';ctx.beginPath();ctx.arc(7,-25,2.5,0,7);ctx.arc(21,-24,2.5,0,7);ctx.fill();if(c===active&&!projectile){const a=(c.angle*Math.PI/180);ctx.rotate(-a);ctx.fillStyle='#37465e';ctx.strokeStyle='#182033';ctx.lineWidth=2;ctx.fillRect(12,-5,23,9);ctx.strokeRect(12,-5,23,9);ctx.fillStyle='#697b94';ctx.fillRect(31,-3,7,5)}ctx.restore()}
function drawHudWorld(c){if(!c.alive)return;ctx.font='800 15px system-ui';ctx.textAlign='center';ctx.fillStyle='#ffffff';ctx.strokeStyle='#102038';ctx.lineWidth=4;ctx.strokeText(c.name,c.x,c.y-42);ctx.fillText(c.name,c.x,c.y-42);ctx.fillStyle='#0c1728aa';ctx.fillRect(c.x-27,c.y-35,54,7);ctx.fillStyle=c.hp>35?'#59df72':'#ff5c53';ctx.fillRect(c.x-27,c.y-35,54*(c.hp/100),7)}
function drawFx(){for(const t of trail){ctx.globalAlpha=Math.max(0,t.life/.6)*.55;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(t.x,t.y,3,0,7);ctx.fill()}ctx.globalAlpha=1;for(const p of particles){ctx.globalAlpha=Math.max(0,Math.min(1,p.life*1.8));ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,7);ctx.fill()}ctx.globalAlpha=1;if(flash>0){ctx.fillStyle=`rgba(255,235,170,${flash*.32})`;ctx.fillRect(0,0,W,H)}}
function render(){ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.82}drawBackground();drawTerrain();drawAimGuide(active);for(const c of worms){drawWorm(c);drawHudWorld(c)}if(projectile){ctx.fillStyle='#2a3342';ctx.beginPath();ctx.arc(projectile.x,projectile.y,7,0,7);ctx.fill();ctx.strokeStyle='#fff4cf';ctx.lineWidth=2;ctx.stroke()}drawFx();ctx.restore();activeNameEl.textContent=active.name;hpEl.textContent=Math.round(active.hp)+' HP';angleEl.textContent=Math.round(active.angle)+'°';powerEl.textContent=Math.round(active.power*100)+'%'}
function update(dt){if(!running)return;playerInput(dt);for(const c of worms)updateCharacter(c,dt);updateProjectile(dt);updateFx(dt);if(phase==='resolve'){turnDelay-=dt;if(turnDelay<=0&&stable())nextTurn()}render()}
function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);requestAnimationFrame(loop)}
for(const b of document.querySelectorAll('[data-hold]')){const k=b.dataset.hold;const on=e=>{e.preventDefault();held.add(k);b.classList.add('active')},off=e=>{e.preventDefault();held.delete(k);b.classList.remove('active')};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)}
for(const b of document.querySelectorAll('[data-tap]'))b.addEventListener('pointerdown',e=>{e.preventDefault();if(b.dataset.tap==='jump')jump()});fireBtn.addEventListener('pointerdown',e=>{e.preventDefault();if(phase==='player')fire(active)});
addEventListener('keydown',e=>{const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'aimUp',ArrowDown:'aimDown',a:'left',d:'right',w:'aimUp',s:'aimDown',q:'powerDown',e:'powerUp'};if(m[e.key])held.add(m[e.key]);if(e.key===' ')jump();if(e.key==='Enter'&&phase==='player')fire(active)});addEventListener('keyup',e=>{const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'aimUp',ArrowDown:'aimDown',a:'left',d:'right',w:'aimUp',s:'aimDown',q:'powerDown',e:'powerUp'};if(m[e.key])held.delete(m[e.key])});
generateTerrain();for(const c of worms)groundCharacter(c);statusEl.textContent='Dein Zug – bewegen, zielen, feuern';resize();requestAnimationFrame(loop);
})();
