(()=>{
'use strict';
const $=s=>document.querySelector(s);
const modal=$('#onlineLobby'),home=$('#onlineHome'),waiting=$('#onlineWaiting'),open=$('#openOnline'),close=$('#closeOnline'),create=$('#createMatch'),join=$('#joinMatch'),joinCode=$('#joinCode'),joinError=$('#joinError'),roomCode=$('#roomCode'),role=$('#waitingRole'),title=$('#waitingTitle'),text=$('#waitingText'),copy=$('#copyRoomCode'),cancel=$('#cancelWaiting');
if(!modal||!open)return;
const style=document.createElement('style');
style.textContent=`
.online-panel{width:min(92vw,480px)}.online-copy{margin:0 0 14px;color:#c7d7e4;font-size:13px}.online-action{width:100%;border:2px solid #6e92ae;border-radius:14px;padding:13px 15px;display:grid;grid-template-columns:42px 1fr;text-align:left;align-items:center;background:linear-gradient(#24455f,#153247);color:#fff;box-shadow:inset 0 1px #ffffff20,0 4px 12px #0005}.online-action.host{border-color:#7dce67;background:linear-gradient(#315c43,#1d3e31)}.online-action>span{font-size:28px;text-align:center}.online-action b,.online-action small{display:block}.online-action b{font-size:16px}.online-action small{font-size:10px;color:#bdd0dd}.online-divider{height:28px;display:flex;align-items:center;gap:10px;color:#7f98aa;font-size:9px;font-weight:900;letter-spacing:.15em}.online-divider:before,.online-divider:after{content:"";height:1px;background:#ffffff20;flex:1}.code-label{font-size:9px;font-weight:900;letter-spacing:.14em;color:#9db4c5}.join-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;margin-top:5px}.code-input{min-width:0;border:2px solid #47647b;border-radius:12px;padding:12px 13px;background:#0a1d2c;color:#fff;text-transform:uppercase;font-weight:950;font-size:18px;letter-spacing:.12em;outline:none}.code-input:focus{border-color:#f1b34a;box-shadow:0 0 0 3px #f1b34a22}.join-btn{width:auto;padding-inline:18px}.join-error{margin-top:7px;color:#ffae95;font-size:10px}.waiting{text-align:center}.waiting>small{font-size:9px;letter-spacing:.15em;color:#9fbbce;font-weight:900}.waiting h3{margin:8px 0 12px;font-size:20px}.room-code{display:inline-block;padding:13px 19px;border-radius:14px;border:2px solid #f1b34a;background:#102a3c;color:#fff;font-size:30px;font-weight:1000;letter-spacing:.13em;box-shadow:0 0 28px #f1b34a24}.copy-code,.secondary-online{display:block;margin:10px auto 0;border:1px solid #57768d;border-radius:10px;background:#19384d;color:#fff;padding:8px 13px;font-weight:900;font-size:10px}.waiting p{margin:15px auto 10px;max-width:340px;color:#b7cbd8;font-size:11px;line-height:1.45}.waiting-dots{height:24px;display:flex;justify-content:center;align-items:center;gap:6px}.waiting-dots i{width:7px;height:7px;border-radius:50%;background:#8bd66e;animation:mwWait 1.1s infinite ease-in-out}.waiting-dots i:nth-child(2){animation-delay:.15s}.waiting-dots i:nth-child(3){animation-delay:.3s}@keyframes mwWait{0%,70%,100%{transform:translateY(0);opacity:.4}35%{transform:translateY(-5px);opacity:1}}.secondary-online{background:#132738;color:#afc1cf}.code-copied{border-color:#77d75d!important;color:#b9f5aa!important}
`;
document.head.appendChild(style);
function reset(){home.classList.remove('hidden');waiting.classList.add('hidden');joinError.classList.add('hidden');joinCode.value='';copy.textContent='CODE KOPIEREN';copy.classList.remove('code-copied')}
function generateCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<4;i++)s+=chars[(Math.random()*chars.length)|0];return 'MW-'+s}
function showWaiting(kind,code){home.classList.add('hidden');waiting.classList.remove('hidden');roomCode.textContent=code;if(kind==='host'){role.textContent='HOST · SPIELER 1';title.textContent='Warte auf Spieler 2…';text.textContent='Öffne Mini-Worms auf dem zweiten Gerät und gib diesen Raumcode unter ONLINE ein.';}else{role.textContent='GAST · SPIELER 2';title.textContent='Verbindung wird gesucht…';text.textContent='V5.0 bereitet die Lobby vor. Die echte Geräteverbindung kommt im nächsten Netzwerkschritt.';}}
open.addEventListener('pointerdown',()=>{reset();modal.classList.remove('hidden')});close.addEventListener('pointerdown',()=>modal.classList.add('hidden'));create.addEventListener('pointerdown',()=>showWaiting('host',generateCode()));
function normalizeCode(){let v=(joinCode.value||'').toUpperCase().replace(/\s+/g,'').replace(/[^A-Z0-9-]/g,'');if(v&&!v.startsWith('MW-')){v=v.replace(/^MW-?/,'');if(v.length<=4)v='MW-'+v}joinCode.value=v.slice(0,7);return joinCode.value}
joinCode.addEventListener('input',normalizeCode);joinCode.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();join.click()}});
join.addEventListener('pointerdown',()=>{const code=normalizeCode();if(!/^MW-[A-Z0-9]{4}$/.test(code)){joinError.classList.remove('hidden');return}joinError.classList.add('hidden');showWaiting('guest',code)});
cancel.addEventListener('pointerdown',reset);
copy.addEventListener('pointerdown',async()=>{const c=roomCode.textContent;try{await navigator.clipboard?.writeText(c);copy.textContent='KOPIERT ✓';copy.classList.add('code-copied')}catch{copy.textContent=c}});
})();