(()=>{
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d',{alpha:false});
const statusEl=document.getElementById('status'),activeNameEl=document.getElementById('activeName'),hpEl=document.getElementById('hpText'),angleEl=document.getElementById('angleText'),powerEl=document.getElementById('powerText'),fireBtn=document.getElementById('fire'),msg=document.getElementById('message');
const W=960,H=540,GROUND=330,GRAV=360; canvas.width=W;canvas.height=H;
let terrain=new Uint8Array(W*H),running=true,last=performance.now(),projectile=null,phase='player',turnDelay=0,shake=0;
const held=new Set();
const worms=[
 {name:'Sheldon',team:'PLAYER',x:150,y:180,vx:0,vy:0,r:16,hp:100,dir:1,angle:42,power:.62,color:'#22c55e',shell:'#78350f',alive:true,onGround:false},
 {name:'Rollridge',team:'CPU',x:790,y:180,vx:0,vy:0,r:17,hp:100,dir:-1,angle:45,power:.58,color:'#38bdf8',shell:'#7c2d12',alive:true,onGround:false}
];
let active=worms[0];
function idx(x,y){return y*W+x} function solid(x,y){x=x|0;y=y|0;return x>=0&&x<W&&y>=0&&y<H&&terrain[idx(x,y)]===1}
function generateTerrain(){terrain.fill(0);for(let x=0;x<W;x++){let surface=GROUND+Math.sin(x*.012)*35+Math.sin(x*.031)*12; surface+=x>400&&x<570?-55:0; for(let y=Math.max(0,surface|0);y<H;y++)terrain[idx(x,y)]=1;} // caves/shape accents
 carveCircle(480,410,52); carveCircle(660,455,38);}
function carveCircle(cx,cy,r){const r2=r*r;for(let y=Math.max(0,(cy-r)|0);y<Math.min(H,(cy+r)|0);y++)for(let x=Math.max(0,(cx-r)|0);x<Math.min(W,(cx+r)|0);x++){let dx=x-cx,dy=y-cy;if(dx*dx+dy*dy<=r2)terrain[idx(x,y)]=0;}}
function resize(){const wrap=canvas.parentElement,rect=wrap.getBoundingClientRect();if(rect.width&&rect.height){canvas.style.width=rect.width+'px';canvas.style.height=rect.height+'px'}} addEventListener('resize',resize);
function terrainSurfaceAt(x){x=Math.max(0,Math.min(W-1,x|0));for(let y=0;y<H;y++)if(solid(x,y))return y;return H;}
function groundCharacter(c){c.y=Math.min(c.y,terrainSurfaceAt(c.x)-c.r-1)}
function circleHitsTerrain(x,y,r){const pts=[[0,r],[r*.75,r*.65],[-r*.75,r*.65],[r,0],[-r,0]];return pts.some(p=>solid(x+p[0],y+p[1]));}
function updateCharacter(c,dt){if(!c.alive)return;c.onGround=circleHitsTerrain(c.x,c.y+2,c.r); if(c.onGround&&c.vy>0)c.vy=0; c.vy+=GRAV*dt; let nx=c.x+c.vx*dt; if(!circleHitsTerrain(nx,c.y,c.r))c.x=nx;else c.vx*=.1; let ny=c.y+c.vy*dt;if(!circleHitsTerrain(c.x,ny,c.r))c.y=ny;else{if(c.vy>0)c.onGround=true;c.vy=0; let guard=0;while(circleHitsTerrain(c.x,c.y,c.r)&&guard++<25)c.y-=1;} c.vx*=Math.pow(.04,dt);if(c.y>H+80){c.hp=0;c.alive=false;}}
function playerInput(dt){if(phase!=='player'||projectile||!active.alive)return;const speed=95;if(held.has('left')){active.vx=-speed;active.dir=-1}if(held.has('right')){active.vx=speed;active.dir=1}if(held.has('aimUp'))active.angle=Math.min(85,active.angle+42*dt);if(held.has('aimDown'))active.angle=Math.max(5,active.angle-42*dt);if(held.has('powerUp'))active.power=Math.min(1,active.power+.45*dt);if(held.has('powerDown'))active.power=Math.max(.18,active.power-.45*dt)}
function jump(){if(phase==='player'&&!projectile&&active.onGround){active.vy=-205;active.onGround=false}}
function muzzle(c){const a=(c.angle*Math.PI/180)*(c.dir);return{x:c.x+Math.cos(a)*28,y:c.y-Math.sin(Math.abs(a))*28,a}}
function fire(c){if(projectile||!c.alive)return;const m=muzzle(c),speed=210+330*c.power;projectile={x:m.x,y:m.y,vx:Math.cos(m.a)*speed,vy:-Math.sin(Math.abs(m.a))*speed,owner:c,life:0};phase='projectile';fireBtn.disabled=true;statusEl.textContent='Projektil fliegt…'}
function explode(x,y,owner){carveCircle(x,y,48);shake=12;for(const c of worms){if(!c.alive)continue;const dx=c.x-x,dy=c.y-y,d=Math.hypot(dx,dy);if(d<110){const t=1-d/110,damage=Math.max(0,Math.round(58*t));c.hp=Math.max(0,c.hp-damage);const inv=1/(d||1);c.vx+=dx*inv*190*t;c.vy+=dy*inv*190*t-90*t;if(c.hp<=0)c.alive=false;}}projectile=null;phase='resolve';turnDelay=1.25;statusEl.textContent='Explosion – Physik wird aufgelöst';}
function updateProjectile(dt){if(!projectile)return;const p=projectile;p.life+=dt;p.vy+=GRAV*.72*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(solid(p.x,p.y)||p.x<0||p.x>=W||p.y>=H){explode(Math.max(0,Math.min(W-1,p.x)),Math.max(0,Math.min(H-1,p.y)),p.owner)}else if(p.life>7){projectile=null;phase='resolve';turnDelay=.7}}
function stable(){return worms.every(c=>!c.alive||(Math.abs(c.vx)<5&&Math.abs(c.vy)<8&&c.onGround))}
function nextTurn(){if(!worms[0].alive||!worms[1].alive){showEnd();return}active=active===worms[0]?worms[1]:worms[0];if(active.team==='CPU'){phase='cpu';fireBtn.disabled=true;statusEl.textContent='Rollridge überlegt…';setTimeout(cpuTurn,700)}else{phase='player';fireBtn.disabled=false;statusEl.textContent='Dein Zug – bewegen, zielen, feuern'}}
function cpuTurn(){if(phase!=='cpu'||!worms[1].alive)return;const c=worms[1],t=worms[0];c.dir=t.x<c.x?-1:1;const dx=Math.abs(t.x-c.x),dy=c.y-t.y;let best={score:1e9,a:45,p:.65};for(let a=20;a<=75;a+=2)for(let p=.35;p<=.95;p+=.05){const speed=210+330*p,vx=Math.cos(a*Math.PI/180)*speed,vy=-Math.sin(a*Math.PI/180)*speed;let x=c.x,y=c.y,xx=vx*c.dir,yy=vy;for(let tt=0;tt<3.2;tt+=.045){xx=xx;yy+=GRAV*.72*.045;x+=xx*.045;y+=yy*.045;if(solid(x,y)||y>H)break;const d=Math.hypot(x-t.x,y-t.y);if(d<best.score)best={score:d,a,p};}}c.angle=best.a;c.power=best.p;setTimeout(()=>fire(c),450)}
function showEnd(){running=false;msg.classList.remove('hidden');msg.innerHTML=worms[0].alive?'SHELDON GEWINNT!<br><small>Tippe zum Neustart</small>':'ROLLRIDGE GEWINNT!<br><small>Tippe zum Neustart</small>';statusEl.textContent='Match beendet';msg.style.pointerEvents='auto';msg.onclick=()=>location.reload()}
function drawTerrain(){const img=ctx.createImageData(W,H),d=img.data;for(let y=0;y<H;y++)for(let x=0;x<W;x++){const i=idx(x,y);if(!terrain[i])continue;const o=i*4,top=!solid(x,y-2);if(top){d[o]=128;d[o+1]=92;d[o+2]=48}else{d[o]=73;d[o+1]=55;d[o+2]=37}d[o+3]=255}ctx.putImageData(img,0,0)}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#60a5fa');g.addColorStop(.7,'#bfdbfe');g.addColorStop(1,'#dbeafe');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffffffcc';for(const c of [[110,90,40],[160,105,52],[720,78,48],[775,92,36]]){ctx.beginPath();ctx.arc(...c,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#ffffff33';ctx.beginPath();ctx.arc(820,85,48,0,7);ctx.fill();}
function drawWorm(c){if(!c.alive)return;ctx.save();ctx.translate(c.x,c.y);ctx.scale(c.dir,1);ctx.strokeStyle='#111827';ctx.lineWidth=3;ctx.fillStyle=c.color;ctx.beginPath();ctx.ellipse(0,5,22,14,0,0,7);ctx.fill();ctx.stroke();ctx.fillStyle=c.shell;ctx.beginPath();ctx.arc(-4,-5,14,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#f8fafc';ctx.beginPath();ctx.arc(10,-10,5,0,7);ctx.arc(18,-9,5,0,7);ctx.fill();ctx.fillStyle='#111827';ctx.beginPath();ctx.arc(12,-10,2,0,7);ctx.arc(20,-9,2,0,7);ctx.fill();ctx.strokeStyle='#111827';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(9,-14);ctx.lineTo(7,-24);ctx.moveTo(18,-13);ctx.lineTo(21,-23);ctx.stroke(); if(c===active&&!projectile){const m=muzzle(c);ctx.restore();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(m.x,m.y);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(m.x,m.y,4,0,7);ctx.fill();return}ctx.restore();}
function drawHudWorld(c){ctx.font='700 16px system-ui';ctx.textAlign='center';ctx.fillStyle='#0f172a';ctx.fillText(c.name,c.x,c.y-38);ctx.fillStyle='#11182788';ctx.fillRect(c.x-25,c.y-32,50,6);ctx.fillStyle=c.hp>35?'#22c55e':'#ef4444';ctx.fillRect(c.x-25,c.y-32,50*(c.hp/100),6)}
function render(){ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.82}drawBackground();drawTerrain();for(const c of worms){drawWorm(c);drawHudWorld(c)}if(projectile){ctx.fillStyle='#111827';ctx.beginPath();ctx.arc(projectile.x,projectile.y,7,0,7);ctx.fill();ctx.strokeStyle='#f8fafc';ctx.lineWidth=2;ctx.stroke()}ctx.restore();activeNameEl.textContent=active.name;hpEl.textContent=Math.round(active.hp)+' HP';angleEl.textContent=Math.round(active.angle)+'°';powerEl.textContent=Math.round(active.power*100)+'%'}
function update(dt){if(!running)return;playerInput(dt);for(const c of worms)updateCharacter(c,dt);updateProjectile(dt);if(phase==='resolve'){turnDelay-=dt;if(turnDelay<=0&&stable())nextTurn()}render()}
function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);requestAnimationFrame(loop)}
for(const b of document.querySelectorAll('[data-hold]')){const k=b.dataset.hold;const on=e=>{e.preventDefault();held.add(k);b.classList.add('active')},off=e=>{e.preventDefault();held.delete(k);b.classList.remove('active')};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)}
for(const b of document.querySelectorAll('[data-tap]'))b.addEventListener('pointerdown',e=>{e.preventDefault();if(b.dataset.tap==='jump')jump()});fireBtn.addEventListener('pointerdown',e=>{e.preventDefault();if(phase==='player')fire(active)});
addEventListener('keydown',e=>{const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'aimUp',ArrowDown:'aimDown',a:'left',d:'right',w:'aimUp',s:'aimDown',q:'powerDown',e:'powerUp'};if(m[e.key])held.add(m[e.key]);if(e.key===' ')jump();if(e.key==='Enter'&&phase==='player')fire(active)});addEventListener('keyup',e=>{const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'aimUp',ArrowDown:'aimDown',a:'left',d:'right',w:'aimUp',s:'aimDown',q:'powerDown',e:'powerUp'};if(m[e.key])held.delete(m[e.key])});
generateTerrain();for(const c of worms)groundCharacter(c);statusEl.textContent='Dein Zug – bewegen, zielen, feuern';resize();requestAnimationFrame(loop);
})();
